services:
  nginx:
    image: nginx:stable-alpine
    container_name: hackhouse-nginx
    network_mode: host
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./http:/etc/nginx/http.d"
      - "./www:/srv/www"
    depends_on:
      - dashbajk-api
    restart: on-failure

  dashbajk-api:
    image: oven/bun:latest
    container_name: rogue-api
    ports:
      - 127.0.0.1:3000:80
    volumes:
      - "./rogue:/app"
    working_dir: /app
    command: bun start
    restart: on-failure