services:
  nginx:
    image: nginx:stable-alpine
    container_name: hackhouse-nginx
    hostname: nginx.hackhouse.lan
    networks:
      - hackhouse
    ports:
      - 80:80
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./http:/etc/nginx/http.d"
      - "./www:/srv/www"
    depends_on:
      - dashbajk-api
    restart: on-failure

  dashbajk-api:
    image: oven/bun:latest
    container_name: rogue-api
    hostname: api.dashbajk.us
    networks:
      - hackhouse
    volumes:
      - "./rogue:/app"
    working_dir: /app
    command: sh -c 'bun install && bun start'
    restart: on-failure
  
networks:
  hackhouse:
    driver: bridge